# Generated by Django 2.0.5 on 2021-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('population', models.IntegerField(null=True)),
                ('usage', models.IntegerField(null=True)),
                ('country_code', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Place Data',
                'verbose_name_plural': 'Place Data',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('entries', models.IntegerField(default=0)),
                ('work1', models.CharField(default='-', max_length=200)),
                ('work2', models.CharField(default='-', max_length=200)),
                ('trans1', models.CharField(default='-', max_length=200)),
                ('trans2', models.CharField(default='-', max_length=200)),
                ('mcom1', models.IntegerField(default=0)),
                ('mcom2', models.IntegerField(default=0)),
                ('results', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
    ]
