# Generated by Django 2.0.5 on 2021-03-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('population', models.IntegerField(null=True)),
                ('usage', models.FloatField(null=True)),
                ('country_code', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('results', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=200)),
                ('transport', models.CharField(max_length=200)),
                ('max_commute', models.IntegerField()),
                ('elements', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='searchresults',
            name='them',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_them', to='mapper.User'),
        ),
        migrations.AddField(
            model_name='searchresults',
            name='you',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_you', to='mapper.User'),
        ),
    ]
